import type { Achievement } from "../model/types";

export const MOCK_ACHIEVEMENTS: Achievement[] = [
  {
    id: 1,
    code: "royal_flush",
    icon: "🃏",
    title: "Royal Flush",
    desc: "Собрал роял-флеш",
    category: "rare",
    unlocked: true,
    date: "2026-04-28",
  },
  {
    id: 2,
    code: "iron_man",
    icon: "📅",
    title: "Iron Man",
    desc: "10 турниров подряд",
    category: "rare",
    unlocked: true,
    date: "2026-04-15",
  },
  {
    id: 3,
    code: "first_win",
    icon: "🥇",
    title: "First Win",
    desc: "Первая победа",
    category: "result",
    unlocked: true,
    date: "2026-03-20",
  },
  {
    id: 4,
    code: "champion_5",
    icon: "🏆",
    title: "Champion ×5",
    desc: "5 побед в турнирах",
    category: "result",
    unlocked: true,
    date: "2026-04-22",
  },
  {
    id: 5,
    code: "regular",
    icon: "🎲",
    title: "Regular",
    desc: "10 турниров",
    category: "participation",
    unlocked: true,
    date: "2026-03-15",
  },
  {
    id: 6,
    code: "veteran",
    icon: "🎲",
    title: "Veteran",
    desc: "50 турниров",
    category: "participation",
    unlocked: false,
  },
  {
    id: 7,
    code: "season_sweep",
    icon: "🏆",
    title: "Season Sweep",
    desc: "Все турниры сезона",
    category: "rare",
    unlocked: false,
  },
  {
    id: 8,
    code: "lightning",
    icon: "⚡",
    title: "Lightning",
    desc: "5+ выбитых в одной раздаче",
    category: "rare",
    unlocked: false,
  },
];
